//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTools.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.SmtInputSoap")]
    public interface SmtInputSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/command_code_for_webservice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string command_code_for_webservice(string vip, int p_cmd, string p_data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/command_code_for_webservice", ReplyAction="*")]
        System.Threading.Tasks.Task<string> command_code_for_webserviceAsync(string vip, int p_cmd, string p_data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SmtInputSoapChannel : MyTools.ServiceReference1.SmtInputSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmtInputSoapClient : System.ServiceModel.ClientBase<MyTools.ServiceReference1.SmtInputSoap>, MyTools.ServiceReference1.SmtInputSoap {
        
        public SmtInputSoapClient() {
        }
        
        public SmtInputSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmtInputSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmtInputSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmtInputSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string command_code_for_webservice(string vip, int p_cmd, string p_data) {
            return base.Channel.command_code_for_webservice(vip, p_cmd, p_data);
        }
        
        public System.Threading.Tasks.Task<string> command_code_for_webserviceAsync(string vip, int p_cmd, string p_data) {
            return base.Channel.command_code_for_webserviceAsync(vip, p_cmd, p_data);
        }
    }
}
